[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

if ($env:OS -ne "Windows_NT") {
    throw "The Windows development lock must be generated on Windows."
}

$pipToolsVersion = "7.6.0"
$repositoryRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$pyprojectPath = Join-Path $repositoryRoot "pyproject.toml"
$lockPath = Join-Path $repositoryRoot "requirements\dev-py313-windows.lock"
$temporaryLockPath = "$lockPath.tmp"
$toolEnvironmentPath = Join-Path $repositoryRoot "out\lock-tools"
$toolPython = Join-Path $toolEnvironmentPath "Scripts\python.exe"
$toolConfig = Join-Path $toolEnvironmentPath "pyvenv.cfg"

function Get-NormalizedTextSha256 {
    param([Parameter(Mandatory = $true)][string]$Path)

    $content = [IO.File]::ReadAllText($Path).Replace("`r`n", "`n").Replace("`r", "`n")
    $encoding = New-Object Text.UTF8Encoding($false)
    $sha256 = [Security.Cryptography.SHA256]::Create()
    try {
        $hashBytes = $sha256.ComputeHash($encoding.GetBytes($content))
    } finally {
        $sha256.Dispose()
    }
    return [BitConverter]::ToString($hashBytes).Replace("-", "").ToLowerInvariant()
}

$requestedPython = & py -3.13 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')"
if ($LASTEXITCODE -ne 0 -or $requestedPython.Trim() -ne "3.13") {
    throw "CPython 3.13 is required to generate the Windows development lock."
}

if (Test-Path -LiteralPath $toolEnvironmentPath) {
    if (
        -not (Test-Path -LiteralPath $toolConfig -PathType Leaf) -or
        -not (Test-Path -LiteralPath $toolPython -PathType Leaf)
    ) {
        throw "Lock-tool path exists but is not a usable Windows venv: $toolEnvironmentPath"
    }
} else {
    New-Item -ItemType Directory -Force -Path (Split-Path $toolEnvironmentPath) | Out-Null
    & py -3.13 -m venv $toolEnvironmentPath
    if ($LASTEXITCODE -ne 0) {
        throw "Python failed to create the lock-tool environment."
    }
}

Write-Host "Ensuring pip-tools==$pipToolsVersion is available in the ignored tool environment"
& $toolPython -m pip install `
    --disable-pip-version-check `
    "pip-tools==$pipToolsVersion"
if ($LASTEXITCODE -ne 0) {
    throw "Installing the pinned lock generator failed."
}

if (Test-Path -LiteralPath $temporaryLockPath -PathType Leaf) {
    Remove-Item -LiteralPath $temporaryLockPath
}

try {
    Push-Location $repositoryRoot
    try {
        & $toolPython -m piptools compile `
            --extra dev `
            --generate-hashes `
            --allow-unsafe `
            --strip-extras `
            --resolver backtracking `
            --no-emit-index-url `
            --no-emit-trusted-host `
            --no-header `
            --newline lf `
            --quiet `
            --output-file "requirements\dev-py313-windows.lock.tmp" `
            "pyproject.toml"
    } finally {
        Pop-Location
    }
    if ($LASTEXITCODE -ne 0) {
        throw "pip-tools failed to compile the development lock."
    }

    $pyprojectHash = Get-NormalizedTextSha256 -Path $pyprojectPath
    $generatedBody = (Get-Content -LiteralPath $temporaryLockPath -Raw).Replace("`r`n", "`n")
    $header = @(
        "# Generated by scripts/update_dev_lock.ps1. Do not edit by hand."
        "# target: Windows CPython 3.13; profile: .[dev]"
        "# generator: pip-tools==$pipToolsVersion"
        "# pyproject-normalized-sha256: $pyprojectHash"
        ""
    ) -join "`n"
    $utf8WithoutBom = New-Object Text.UTF8Encoding($false)
    [IO.File]::WriteAllText($lockPath, "$header`n$generatedBody", $utf8WithoutBom)
} finally {
    if (Test-Path -LiteralPath $temporaryLockPath -PathType Leaf) {
        Remove-Item -LiteralPath $temporaryLockPath
    }
}

Write-Host "Generated $lockPath"
Write-Host "Review the dependency and hash diff before committing it."
