"""Generate one installed-first-run configuration for Desktop Ask."""
from __future__ import annotations

import json
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

from .config import (
    AgentConfig,
    ContinuationConfig,
    MCPLaunchConfig,
    PolicyConfig,
    ProviderConfig,
    default_state_dir,
)


class ConfigInitError(ValueError):
    """Raised when a starter configuration cannot be created."""


@dataclass(frozen=True)
class InitializedConfig:
    """Safe metadata describing one newly created starter configuration."""

    output: Path
    state_dir: Path
    mcp_executable: Path
    provider: str
    model: str

    def as_json(self) -> dict[str, object]:
        return {
            "created": True,
            "output": str(self.output),
            "state_dir": str(self.state_dir),
            "mcp_executable": str(self.mcp_executable),
            "provider": self.provider,
            "model": self.model,
            "policy_mode": "read_only",
            "config_valid": True,
        }


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _resolve_mcp_executable(explicit: Path | None) -> Path:
    candidates: tuple[Path, ...]
    if explicit is not None:
        candidates = (explicit.expanduser().resolve(strict=False),)
    else:
        script_name = "guarded-desktop-mcp.exe" if sys.platform == "win32" else "guarded-desktop-mcp"
        sibling = Path(sys.executable).resolve(strict=False).with_name(script_name)
        discovered = shutil.which("guarded-desktop-mcp")
        candidates = (sibling,) if discovered is None else (sibling, Path(discovered))
    for candidate in candidates:
        resolved = candidate.resolve(strict=False)
        if resolved.is_file():
            return resolved
    raise ConfigInitError(
        "MCP_EXECUTABLE_NOT_FOUND: install the package or pass --mcp-executable"
    )


def _render_config(config: AgentConfig) -> str:
    provider = config.provider
    policy = config.policy
    continuation = config.continuation
    allowlist = config.mcp.environment["CUMCP_ALLOWLIST"]
    return f"""\
# Generated by `guarded-desktop-agent config init` for bounded Desktop Ask.
# Provider credentials stay in the host process environment and are never written here.

[agent]
state_dir = {_toml_string(config.state_dir.as_posix())}
policy_version = "readonly-v1"

[provider]
name = {_toml_string(provider.name)}
model = {_toml_string(provider.model)}
max_request_bytes = {provider.max_request_bytes}
context_window_tokens = {provider.context_window_tokens}
output_token_reserve = {provider.output_token_reserve}

[mcp]
executable = {_toml_string(config.mcp.executable.as_posix())}
args = []
cwd = {_toml_string(config.mcp.cwd.as_posix())}
environment = {{ CUMCP_ALLOWLIST = {_toml_string(allowlist)} }}

[policy]
mode = "read_only"
require_approval_for_actions = true
max_model_turns = {policy.max_model_turns}
max_tool_calls = {policy.max_tool_calls}
max_side_effects = {policy.max_side_effects}
max_input_tokens = {policy.max_input_tokens}
max_context_events = {policy.max_context_events}

[continuation]
# Desktop Ask requires its bounded observation/final-response WAL.
enabled = true
ttl_seconds = {continuation.ttl_seconds}
"""


def initialize_desktop_ask_config(
    *,
    provider: str,
    model: str,
    output: Path,
    allowlist: str = "notepad.exe",
    mcp_executable: Path | None = None,
) -> InitializedConfig:
    """Create one non-overwriting, immediately valid read-only configuration."""

    output_path = output.expanduser().resolve(strict=False)
    if output_path.exists():
        raise ConfigInitError("CONFIG_OUTPUT_EXISTS")
    if not output_path.parent.is_dir():
        raise ConfigInitError("CONFIG_OUTPUT_PARENT_NOT_FOUND")

    executable = _resolve_mcp_executable(mcp_executable)
    state_dir = default_state_dir().resolve(strict=False)
    config = AgentConfig(
        state_dir=state_dir,
        policy_version="readonly-v1",
        provider=ProviderConfig(name=provider, model=model),
        mcp=MCPLaunchConfig(
            executable=executable,
            args=(),
            cwd=state_dir,
            environment={"CUMCP_ALLOWLIST": allowlist},
        ),
        policy=PolicyConfig(),
        continuation=ContinuationConfig(enabled=True),
    )

    state_dir.mkdir(parents=True, exist_ok=True)
    try:
        with output_path.open("x", encoding="utf-8", newline="\n") as file:
            file.write(_render_config(config))
    except FileExistsError as exc:
        raise ConfigInitError("CONFIG_OUTPUT_EXISTS") from exc

    return InitializedConfig(
        output=output_path,
        state_dir=config.state_dir,
        mcp_executable=executable,
        provider=config.provider.name,
        model=config.provider.model,
    )


__all__ = [
    "ConfigInitError",
    "InitializedConfig",
    "initialize_desktop_ask_config",
]
