"""Generate one installed-first-run configuration for Desktop Ask."""
from __future__ import annotations

import json
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

from .config import (
    APPROVED_ACTIONS_MODE,
    AgentConfig,
    ContinuationConfig,
    MCPLaunchConfig,
    OperatorConfig,
    PolicyConfig,
    ProviderConfig,
    default_state_dir,
)

DESKTOP_ASK_PROFILE = "desktop-ask"
PUBLIC_WEB_WORD_PROFILE = "public-web-word"
SUPPORTED_INIT_PROFILES = frozenset(
    {DESKTOP_ASK_PROFILE, PUBLIC_WEB_WORD_PROFILE}
)


class ConfigInitError(ValueError):
    """Raised when a starter configuration cannot be created."""


@dataclass(frozen=True)
class InitializedConfig:
    """Safe metadata describing one newly created starter configuration."""

    output: Path
    state_dir: Path
    mcp_executable: Path
    provider: str
    model: str
    profile: str
    policy_mode: str

    def as_json(self) -> dict[str, object]:
        return {
            "created": True,
            "output": str(self.output),
            "state_dir": str(self.state_dir),
            "mcp_executable": str(self.mcp_executable),
            "provider": self.provider,
            "model": self.model,
            "profile": self.profile,
            "policy_mode": self.policy_mode,
            "config_valid": True,
        }


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _default_product_operator(*, decision_timeout_seconds: int = 300) -> OperatorConfig:
    """Enable every current UI/UX preference in a newly generated profile."""

    return OperatorConfig(
        presence_enabled=True,
        progress_enabled=True,
        reduced_motion=True,
        high_contrast=True,
        decision_cards_enabled=True,
        approval_notifications_enabled=True,
        locale="auto",
        theme="auto",
        decision_timeout_seconds=decision_timeout_seconds,
    )


def resolve_mcp_executable(explicit: Path | None) -> Path:
    candidates: tuple[Path, ...]
    if explicit is not None:
        candidates = (explicit.expanduser().resolve(strict=False),)
    else:
        script_name = "guarded-desktop-mcp.exe" if sys.platform == "win32" else "guarded-desktop-mcp"
        sibling = Path(sys.executable).resolve(strict=False).with_name(script_name)
        discovered = shutil.which("guarded-desktop-mcp")
        candidates = (sibling,) if discovered is None else (sibling, Path(discovered))
    for candidate in candidates:
        resolved = candidate.resolve(strict=False)
        if resolved.is_file():
            return resolved
    raise ConfigInitError(
        "MCP_EXECUTABLE_NOT_FOUND: install the package or pass --mcp-executable"
    )


def _render_config(config: AgentConfig, *, profile: str) -> str:
    provider = config.provider
    policy = config.policy
    continuation = config.continuation
    rendered_environment = ", ".join(
        f"{key} = {_toml_string(value)}"
        for key, value in sorted(config.mcp.environment.items())
    )
    operator = config.operator
    return f"""\
# Generated by `guarded-desktop-agent config init` for {profile}.
# Provider credentials stay in the host process environment and are never written here.

[agent]
state_dir = {_toml_string(config.state_dir.as_posix())}
policy_version = {_toml_string(config.policy_version)}

[provider]
name = {_toml_string(provider.name)}
model = {_toml_string(provider.model)}
max_request_bytes = {provider.max_request_bytes}
context_window_tokens = {provider.context_window_tokens}
output_token_reserve = {provider.output_token_reserve}
request_timeout_seconds = {provider.request_timeout_seconds}

[mcp]
executable = {_toml_string(config.mcp.executable.as_posix())}
args = []
cwd = {_toml_string(config.mcp.cwd.as_posix())}
environment = {{ {rendered_environment} }}

[policy]
mode = {_toml_string(policy.mode)}
require_approval_for_actions = {str(policy.require_approval_for_actions).lower()}
max_model_turns = {policy.max_model_turns}
max_tool_calls = {policy.max_tool_calls}
max_side_effects = {policy.max_side_effects}
max_input_tokens = {policy.max_input_tokens}
max_context_events = {policy.max_context_events}

[continuation]
# Desktop Ask uses its bounded WAL; typed product workflows stay ephemeral.
enabled = {str(continuation.enabled).lower()}
ttl_seconds = {continuation.ttl_seconds}

[operator]
presence_enabled = {str(operator.presence_enabled).lower()}
progress_enabled = {str(operator.progress_enabled).lower()}
reduced_motion = {str(operator.reduced_motion).lower()}
high_contrast = {str(operator.high_contrast).lower()}
decision_cards_enabled = {str(operator.decision_cards_enabled).lower()}
approval_notifications_enabled = {str(operator.approval_notifications_enabled).lower()}
locale = {_toml_string(operator.locale)}
theme = {_toml_string(operator.theme)}
decision_timeout_seconds = {operator.decision_timeout_seconds}
decision_card_corner = {_toml_string(operator.decision_card_corner)}
"""


def initialize_desktop_ask_config(
    *,
    provider: str,
    model: str,
    output: Path,
    allowlist: str = "notepad.exe",
    mcp_executable: Path | None = None,
) -> InitializedConfig:
    """Create one non-overwriting, immediately valid read-only configuration."""

    output_path = output.expanduser().resolve(strict=False)
    if output_path.exists():
        raise ConfigInitError("CONFIG_OUTPUT_EXISTS")
    if not output_path.parent.is_dir():
        raise ConfigInitError("CONFIG_OUTPUT_PARENT_NOT_FOUND")

    executable = resolve_mcp_executable(mcp_executable)
    state_dir = default_state_dir().resolve(strict=False)
    config = AgentConfig(
        state_dir=state_dir,
        policy_version="readonly-v1",
        provider=ProviderConfig(name=provider, model=model),
        mcp=MCPLaunchConfig(
            executable=executable,
            args=(),
            cwd=state_dir,
            environment={
                "CUMCP_ACTION_FEEDBACK": "1",
                "CUMCP_ALLOWLIST": allowlist,
            },
        ),
        policy=PolicyConfig(),
        continuation=ContinuationConfig(enabled=True),
        operator=_default_product_operator(),
    )

    state_dir.mkdir(parents=True, exist_ok=True)
    try:
        with output_path.open("x", encoding="utf-8", newline="\n") as file:
            file.write(_render_config(config, profile=DESKTOP_ASK_PROFILE))
    except FileExistsError as exc:
        raise ConfigInitError("CONFIG_OUTPUT_EXISTS") from exc

    return InitializedConfig(
        output=output_path,
        state_dir=config.state_dir,
        mcp_executable=executable,
        provider=config.provider.name,
        model=config.provider.model,
        profile=DESKTOP_ASK_PROFILE,
        policy_mode=config.policy.mode,
    )


def initialize_public_web_word_config(
    *,
    provider: str,
    model: str,
    output: Path,
    mcp_executable: Path | None = None,
) -> InitializedConfig:
    """Create one supervised action config for the installed fixed workflow."""

    output_path = output.expanduser().resolve(strict=False)
    if output_path.exists():
        raise ConfigInitError("CONFIG_OUTPUT_EXISTS")
    if not output_path.parent.is_dir():
        raise ConfigInitError("CONFIG_OUTPUT_PARENT_NOT_FOUND")

    executable = resolve_mcp_executable(mcp_executable)
    state_dir = (default_state_dir() / "public-web-word").resolve(strict=False)
    config = AgentConfig(
        state_dir=state_dir,
        policy_version="public-web-word-v1",
        provider=ProviderConfig(
            name=provider,
            model=model,
            request_timeout_seconds=90,
        ),
        mcp=MCPLaunchConfig(
            executable=executable,
            args=(),
            cwd=state_dir,
            environment={
                "CUMCP_ACTION_FEEDBACK": "1",
                "CUMCP_ALLOWLIST": "chrome.exe,winword.exe",
                # A Decision Card click is human input. Keep the action inside
                # its single MCP call until the operator has released control.
                "CUMCP_HUMAN_MAX_WAIT_SECONDS": "15",
                "CUMCP_HUMAN_STABLE_SAMPLES": "3",
            },
        ),
        policy=PolicyConfig(
            mode=APPROVED_ACTIONS_MODE,
            max_model_turns=28,
            max_tool_calls=24,
            max_side_effects=7,
        ),
        continuation=ContinuationConfig(enabled=False),
        operator=_default_product_operator(decision_timeout_seconds=180),
    )
    state_dir.mkdir(parents=True, exist_ok=True)
    try:
        with output_path.open("x", encoding="utf-8", newline="\n") as file:
            file.write(_render_config(config, profile=PUBLIC_WEB_WORD_PROFILE))
    except FileExistsError as exc:
        raise ConfigInitError("CONFIG_OUTPUT_EXISTS") from exc
    return InitializedConfig(
        output=output_path,
        state_dir=config.state_dir,
        mcp_executable=executable,
        provider=config.provider.name,
        model=config.provider.model,
        profile=PUBLIC_WEB_WORD_PROFILE,
        policy_mode=config.policy.mode,
    )


def initialize_agent_config(
    *,
    profile: str,
    provider: str,
    model: str,
    output: Path,
    allowlist: str | None = None,
    mcp_executable: Path | None = None,
) -> InitializedConfig:
    """Route one closed product profile without widening its defaults."""

    if profile == DESKTOP_ASK_PROFILE:
        return initialize_desktop_ask_config(
            provider=provider,
            model=model,
            output=output,
            allowlist=allowlist or "notepad.exe",
            mcp_executable=mcp_executable,
        )
    if profile == PUBLIC_WEB_WORD_PROFILE:
        if allowlist is not None:
            raise ConfigInitError("PUBLIC_WEB_WORD_ALLOWLIST_FIXED")
        return initialize_public_web_word_config(
            provider=provider,
            model=model,
            output=output,
            mcp_executable=mcp_executable,
        )
    raise ConfigInitError("CONFIG_PROFILE_NOT_IMPLEMENTED")


__all__ = [
    "ConfigInitError",
    "DESKTOP_ASK_PROFILE",
    "InitializedConfig",
    "PUBLIC_WEB_WORD_PROFILE",
    "SUPPORTED_INIT_PROFILES",
    "initialize_agent_config",
    "initialize_desktop_ask_config",
    "initialize_public_web_word_config",
    "resolve_mcp_executable",
]
